spring: 
  profiles: 
    active: 
    - dev
---
server: 
  port: 8001
spring: 
  profiles: dev
  application: 
    name: msc-config-goods-client
  datasource: 
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://127.0.0.1:3306/cloudDB01
    username: root
    password: 123456
    dbcp2: 
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 200
mybatis:
  config-location: classpath:mybatis/mybatis-cfg.xml
  type-aliases-package: com.gxw.msc.entity
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml
eureka:
  client: 
    service-url: 
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka
  instance: 
    instance-id: goods-8001.com
    prefer-ip-address: true
info:
  app.name: gxw-msc
  company.name: www.gxw.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$
---
server: 
  port: 8001
spring: 
  profiles: test
  application: 
    name: msc-config-goods-client
  datasource: 
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://127.0.0.1:3306/cloudDB03
    username: root
    password: 123456
    dbcp2: 
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 200
mybatis:
  config-location: classpath:mybatis/mybatis-cfg.xml
  type-aliases-package: com.gxw.msc.entity
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml
eureka:
  client: 
    service-url: 
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka
  instance: 
    instance-id: goods-8001.com
    prefer-ip-address: true
info:
  app.name: gxw-msc
  company.name: www.gxw.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$
